addSbtPlugin("org.jetbrains"    % "sbt-ide-settings"     % "1.1.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.4.6")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"         % "0.9.34")
addSbtPlugin("com.codecommit"   % "sbt-spiewak-sonatype" % "0.23.0")
addCompilerPlugin("com.olegpy" %% "better-monadic-for"   % "0.3.1" % "test")
